os: linux
arch:
 - amd64
 - ppc64le
language: c

# Setting sudo access to false will let Travis CI use containers
# rather than VMs to run the tests. For more details see:
# https://docs.travis-ci.com/user/reference/overview/
sudo: false

script:
  - cd tests
  - ./unittest.sh
  - cd ../examples
  - ./cpptest.sh
  - git diff --exit-code
